/* Generated by Cython 0.24 */

#ifndef __PYX_HAVE__pcontainers___py_exceptions
#define __PYX_HAVE__pcontainers___py_exceptions


#ifndef __PYX_HAVE_API__pcontainers___py_exceptions

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) __pyx_f_11pcontainers_14_py_exceptions_custom_handler(void);

__PYX_EXTERN_C DL_IMPORT(PyObject) *py_lmdb_error;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_not_initialized;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_access_error;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_key_exist;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_not_found;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_empty_key;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_empty_database;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_page_not_found;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_corrupted;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_panic;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_version_mismatch;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_invalid;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_map_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_dbs_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_readers_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_tls_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_txn_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_cursor_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_page_full;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_map_resized;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_incompatible;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_bad_rslot;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_bad_txn;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_bad_val_size;
__PYX_EXTERN_C DL_IMPORT(PyObject) *py_bad_dbi;

#endif /* !__PYX_HAVE_API__pcontainers___py_exceptions */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_py_exceptions(void);
#else
PyMODINIT_FUNC PyInit__py_exceptions(void);
#endif

#endif /* !__PYX_HAVE__pcontainers___py_exceptions */
